### ISSUE TITLE
Stripping Metadata

### ISSUE THREAD

**Issue by axyz** [zalando-stups/skrop#92]
currently image.Process will not strip image metadata.
We could either default to strip it here https://github.com/zalando-stups/skrop/blob/d97836a0ad1e592cabc85e52dce336a2b5b790f3/filters/imagefilter.go#L194 in order to have a smaller default output

or we can provide a filter to add the required option.

**Comment by aryszka** [comment]
it's also possible to define a global, cmd option for stripping/not-stripping, and create a filter that only overrides this behavior, e.g. stripMeta("true")

this way it is possible to better support different use cases. What do you think, does this make sense?

**Comment by axyz** [comment]
yeah I think the global option would be nice as most likely you want to strip all the configs and don't want to repeat it everywhere. And being an additional option will not break for backwards compatibility

**Comment by aryszka** [comment]
agree :+1:
